name: cesium_3d_tiles
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.2
  http: ^1.2.2
  vector_math: ^2.1.4
  native_toolchain_c: ^0.4.2
  archive: ^3.6.1
  native_assets_cli: ^0.6.1
  logging: ^1.3.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  ffigen: ^12.0.0
  path: ^1.9.0

