name: cesium_3d_native
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0-134.0.dev

# Add regular dependencies here.
dependencies:
  native_toolchain_c: ^0.4.2
  ffi: ^2.1.2
  http: ^1.2.2
  

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  ffigen: ^12.0.0
